id: P001766
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:20:14.969272
source_metadata:
  id: bdr:W1KG3830
  title: ཆོས་རྗེ་ཀརྨ་པ་སྐུ་འཕྲེང་རིམ་བྱོན་གྱི་རྣམ་ཐར་མདོར་བསྡུས་དཔག་བསམ་ཁྲི་ཤིང
  author: ''
  volumes:
    93c8e5f62b014f86866c6ead4112e9e4:
      image_group_id: I1KG3891
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
