id: I378C507B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T11:30:30+00:00'
last_modified: '2022-06-07T15:04:31.778277+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3830
  title: ཆོས་རྗེ་ཀརྨ་པ་སྐུ་འཕྲེང་རིམ་བྱོན་གྱི་རྣམ་ཐར་མདོར་བསྡུས་དཔག་བསམ་ཁྲི་ཤིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    57B9:
      image_group_id: I1KG3891
      title: ''
      total_pages: 474
      order: 1
      base_file: 57B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
